name: Run detect-secrets with reviewdog
description: 🐶 Run detect-secrets with reviewdog on pull requests to improve code review experience.
inputs:
  github_token:
    description: GITHUB_TOKEN
    default: ${{ github.token }}
  name:
    description: Report name
    default: detect-secrets
  workdir:
    description: "The directory from which to look for and run detect-secrets. Default: '.'"
    default: "."
  filter_mode:
    description: Reviewdog filter mode [added, diff_context, file, nofilter]
    default: added
  fail_on_error:
    description: Whether reviewdog should fail when errors are found. [true,false] - This is useful for failing CI builds.
    default: "false"
  level:
    description: Report level for reviewdog [info,warning,error]
    default: error
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: github-pr-check
  reviewdog_flags:
    description: Additional reviewdog flags
    default: ""
  detect_secrets_flags:
    description: Flags and args of detect-secrets command. The default is '--all-files --force-use-all-plugins'.
    default: --all-files --force-use-all-plugins
  baseline_path:
    description: The baseline path to update. If not provided, a new baseline will be created.
    default: ""
runs:
  using: docker
  image: Dockerfile
branding:
  icon: shield
  color: green
